ALTER TABLE indicators ADD COLUMN IF NOT EXISTS rsi_14 DECIMAL;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS bb_upper DECIMAL;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS bb_middle DECIMAL;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS bb_lower DECIMAL;
